language: scala
scala:
  - 2.10.4
  - 2.11.5

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk7

branches:
  only:
    - SFX-2
    - SFX-2-stable

notifications:
  email:
    - scalafx-build@googlegroups.com

